CREATE TABLE `tbl_pass_det_v2` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `pname` VARCHAR(255) NOT NULL,
  `ph_num` VARCHAR(50) DEFAULT NULL,
  `age_val` VARCHAR(10) DEFAULT NULL,
  `bk_status` VARCHAR(20) DEFAULT 'WAIT',
  `created_dt` DATETIME DEFAULT CURRENT_TIMESTAMP
);
